blog/urls.py
from django.urls import path
from .views import reder_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', reder_posts, name='posts'),
    path('<post_id>', post_detail, name="post_detail"),
]

django_portafolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from portafolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

# Configuración para servir archivos de medios durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def reder_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portafolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}


<div class="text-center">
    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date|date:"F j, Y" }}</h3>

    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">

    <div class="my-4">
        <p>{{ post.description|safe }}</p>
    </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<h1>Publicaciones</h1>

{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{ post.title }}</h2>
                <p>{{ post.description|striptags|truncatechars:100 }}</p>
                <p>{{ post.date|date:'M d Y'|upper }}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{ post.title }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<div class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portafolio/profile.jpg' %}" alt="Imagen de perfil" />
    </div>

    <div class="col-md-8 my-auto">
        <h1>Soy <strong>Oscar Javier Castelblanco</strong></h1>
        <h3>Ingeniero de datos con 7 años de experiencia en el analisis de datos. Me enfoco en el desarrollo
            de soluciones integrales, desde la manipulación y análisis de datos hasta la creación de procesos ETL,
            Visualización de datos, Backend, API_RES.
            escalables.</h3>
        <p>Trabajo en la construcción de sistemas funcionales y eficientes, utilizando microservicios y APIs
            empresariales para integrar datos de diversas fuentes.</p>
        <a href="https://www.linkedin.com/in/oscar-javier-castelblanco-quintero-556b55b1/"
            class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">LinkedIn</a>

    </div>
</div>

<div class="row my-4 text-center">

    <h3>PROYECTOS</h3>
    <p>click para ver un proyecto... 👽🛸👽</p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
        <div class="card bg-black text-white card-project">
            <img src="{{ project.image.url }}" alt="Imagen del proyecto {{ project.title }}" class="card-img-top" />
            <div class="card-body">

                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
                {% if project.url %}
                <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{ project.url }}</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css'%}" </head>

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/">Oscar Javier Castelblanco Quintero</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/blog">Blog</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'portafolio/CV_ES.pdf' %}"
                        target="_blank">Download CV_ES</a>
                </li>
                <li class="nav-item ms-3 d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'portafolio/CV_EN.pdf' %}"
                        target="_blank">Download CV_EN</a>
                </li>
            </ul>
        </div>
    </div>
</nav>